"""initial schema

Revision ID: f4912cad95c6
Revises: 
Create Date: 2026-08-10 16:26:57.537461
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f4912cad95c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_permissions'))
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('workspace_path', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('study_plans',
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('outline', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    op.create_table('workspace_roots',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('writable', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_roots')),
    sa.UniqueConstraint('path', name=op.f('uq_workspace_roots_path'))
    )
    op.create_table('conversations',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('provider_id', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summarized_through', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_conversations_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_archived_last_message', ['archived', 'last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('stored_path', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('model_description', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_experiments_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('learning_progress',
    sa.Column('study_plan_id', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], name=op.f('fk_learning_progress_study_plan_id_study_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_progress'))
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_study_plan_id'), ['study_plan_id'], unique=False)

    op.create_table('project_tasks',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_tasks'))
    )
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('memories',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_memories_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memories_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_project_id'), ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_message_conversation_sequence')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('experiment_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_simulation_runs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulation_runs'))
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_experiment_id'), ['experiment_id'], unique=False)

    op.create_table('task_runs',
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_task_runs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs'))
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_status'), ['status'], unique=False)

    op.create_table('tool_calls',
    sa.Column('conversation_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('approval', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_tool_calls_conversation_id_conversations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_calls_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_calls_tool_name'), ['tool_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_calls_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_task_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_message_id'))
        batch_op.drop_index(batch_op.f('ix_tool_calls_conversation_id'))

    op.drop_table('tool_calls')
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runs_status'))
        batch_op.drop_index(batch_op.f('ix_task_runs_conversation_id'))

    op.drop_table('task_runs')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_experiment_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_project_id'))
        batch_op.drop_index(batch_op.f('ix_memories_kind'))

    op.drop_table('memories')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tasks_project_id'))

    op.drop_table('project_tasks')
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_study_plan_id'))

    op.drop_table('learning_progress')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index('ix_conversations_archived_last_message')

    op.drop_table('conversations')
    op.drop_table('workspace_roots')
    op.drop_table('study_plans')
    op.drop_table('settings')
    op.drop_table('projects')
    op.drop_table('permissions')
    # ### end Alembic commands ###
